services:
  ansible:
    build: ./ansible
    container_name: ansible
    volumes:
      - ./ansible:/ansible
    working_dir: /ansible
    command: tail -f /dev/null
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - node5
      - node6
      - node7
      - node8
      - node9


  node1:
    image: rastasheep/ubuntu-sshd:18.04
    container_name: node1
    environment:
      - ROOT_PASSWORD=root

  node2:
    image: rastasheep/ubuntu-sshd:18.04
    container_name: node2
    environment:
      - ROOT_PASSWORD=root

  node3:
    image: rastasheep/ubuntu-sshd:18.04
    container_name: node3
    environment:
      - ROOT_PASSWORD=root
 
  node4:
    image: rastasheep/ubuntu-sshd:18.04
    container_name: node4
    environment:
      - ROOT_PASSWORD=root

  node5:
    image: rastasheep/ubuntu-sshd:18.04
    container_name: node5
    environment:
      - ROOT_PASSWORD=root

  node6:
    image: rastasheep/ubuntu-sshd:18.04
    container_name: node6
    environment:
      - ROOT_PASSWORD=root

  node7:
    image: rastasheep/ubuntu-sshd:18.04
    container_name: node7
    environment:
      - ROOT_PASSWORD=root

  node8:
    image: rastasheep/ubuntu-sshd:18.04
    container_name: node8
    environment:
      - ROOT_PASSWORD=root

  node9:
    image: rastasheep/ubuntu-sshd:18.04
    container_name: node9
    environment:
      - ROOT_PASSWORD=root
