- name: Пример использования with_items
  hosts: all
  become: yes
  tasks:

    - name: Установить несколько пакетов
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - curl
        - htop
        - git
